### ISSUE TITLE
CDN报错：“module”未定义

### ISSUE THREAD

**Issue by saintsf** [imtaotao/danmuku#4]
<script src="https://cdn.jsdelivr.net/npm/@rustle/danmuku"></script>
Uncaught ReferenceError: module is not defined
at danmuku.common.js:1251

**Comment by imtaotao** [comment]
默认是拿的 cjs 的，用下面这个，是 umd 的。
`https://cdn.jsdelivr.net/npm/@rustle/danmuku/dist/danmuku.min.js`

**Comment by saintsf** [comment]
> 默认是拿的 cjs 的，用下面这个，是 umd 的。
> `https://cdn.jsdelivr.net/npm/@rustle/danmuku/dist/danmuku.min.js`

谢谢
